id: hl7.fhir.fr.core
canonical: http://hl7.fr/ig/fhir/core
name: ExampleIG
title: Exemple d'IG Français
publisher:
  name: Interop'Santé
  url: http://interopsante.org/
status: draft
version: 2.0.0
fhirVersion: 4.0.1
copyrightYear: 2023+
releaseLabel: ci-build

